### ISSUE TITLE
Image in sub folder is not found

### ISSUE THREAD

**Issue by eli191** [bnoffer/XamExtensionsSvg#1]
**Describe the bug**
Hi,
The image is found in the Resources folder but not in a sub folder like image/colours.svg.
Maybe this is a future feature?
Thanks

**To Reproduce**

```
Error while trying to load Resource Id
Value cannot be null.
Parameter name: name
```

**Expected behavior**
The image would show

**Screenshots**

**ownCloud / NextCloud version (required):**
ownCloud 8.2

**Additional context**

**Comment by bnoffer** [comment]
Is the file in the subfolder actually marked as EmbeddedResource? And ensure that the library is initialized, if that is not done this will also occur. As you can see [here](https://github.com/bnoffer/XamExtensionsSvg/blob/2e38c82c660f6529f21a6bd17574a123d0fe1166/XamExtensionsSvg/SvgImage.cs#L114) the path itself is ignored since we are just looking for the filename.

**Comment by bnoffer** [comment]
Closing this issue due to no further feedback.
